[package]
name = "maximum-number-that-sum-of-the-prices-is-less-than-or-equal-to-k"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
